"""Centralized environment variable loading for graphragX."""

from __future__ import annotations

import os

from helpers.constants import (
    DEEPSEEK_API_KEY_ENV_NAME,
    DEEPSEEK_BASE_URL_ENV_NAME,
    DEFAULT_DEEPSEEK_BASE_URL,
    DEFAULT_LOGGING_COLOR,
    DEFAULT_LOGGING_LEVEL,
    DEFAULT_QDRANT_COLLECTION_PREFIX,
    DEFAULT_QDRANT_URL,
    DEFAULT_WANDB_MODE,
    DEFAULT_WANDB_PROJECT,
    LOGGING_COLOR_ENV_NAME,
    LOGGING_LEVEL_ENV_NAME,
    OPENAI_API_KEY_ENV_NAME,
    VEZILKA_API_KEY_ENV_NAME,
    QDRANT_API_KEY_ENV_NAME,
    QDRANT_COLLECTION_PREFIX_ENV_NAME,
    QDRANT_URL_ENV_NAME,
    WANDB_ENTITY_ENV_NAME,
    WANDB_MODE_ENV_NAME,
    WANDB_PROJECT_ENV_NAME,
)

try:
    from dotenv import load_dotenv
except ModuleNotFoundError:
    load_dotenv = None

if load_dotenv is not None:
    load_dotenv()

OPENAI_API_KEY = os.getenv(OPENAI_API_KEY_ENV_NAME)
DEEPSEEK_API_KEY = os.getenv(DEEPSEEK_API_KEY_ENV_NAME)
DEEPSEEK_BASE_URL = os.getenv(DEEPSEEK_BASE_URL_ENV_NAME) or DEFAULT_DEEPSEEK_BASE_URL
VEZILKA_API_KEY = os.getenv(VEZILKA_API_KEY_ENV_NAME)
GRAPHRAGX_LOG_LEVEL = os.getenv(
    LOGGING_LEVEL_ENV_NAME,
    DEFAULT_LOGGING_LEVEL,
).upper()
GRAPHRAGX_LOG_COLOR = os.getenv(
    LOGGING_COLOR_ENV_NAME,
    DEFAULT_LOGGING_COLOR,
).lower()
WANDB_PROJECT = os.getenv(WANDB_PROJECT_ENV_NAME) or DEFAULT_WANDB_PROJECT
WANDB_ENTITY = os.getenv(WANDB_ENTITY_ENV_NAME) or None
WANDB_MODE = os.getenv(WANDB_MODE_ENV_NAME) or DEFAULT_WANDB_MODE
QDRANT_URL = os.getenv(QDRANT_URL_ENV_NAME) or DEFAULT_QDRANT_URL
QDRANT_API_KEY = os.getenv(QDRANT_API_KEY_ENV_NAME) or None
QDRANT_COLLECTION_PREFIX = (
    os.getenv(QDRANT_COLLECTION_PREFIX_ENV_NAME) or DEFAULT_QDRANT_COLLECTION_PREFIX
)
