"""Public pipeline exports for graphragX.

This module uses lazy exports so moving phase-specific services under
``pipeline.preparation`` does not create circular imports through package
``__init__`` files.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORT_MODULES: dict[str, str] = {
    "AbstractStep": "pipeline.abstract",
    "StepContext": "pipeline.abstract",
    "StepResult": "pipeline.abstract",
    "StepContextBuilder": "pipeline.context_builder",
    "InitialStepResult": "pipeline.models",
    "PipelineExecutionResult": "pipeline.models",
    "PipelineResultBank": "pipeline.models",
    "Pipeline": "pipeline.pipeline",
    "AbstractService": "pipeline.services",
    "PipelineException": "pipeline.exceptions",
    "PipelineExecutionException": "pipeline.exceptions",
    "StepNotImplementedException": "pipeline.exceptions",
    "BuildGnnAnswerRetrieverContext": "pipeline.preparation",
    "BuildGnnAnswerRetrieverStep": "pipeline.preparation",
    "BuildPipelineConfigurationStep": "pipeline.preparation",
    "BuildWebQSPLocalGraphsStep": "pipeline.preparation",
    "BuiltGnnAnswerRetriever": "pipeline.preparation",
    "BuiltPipelineConfiguration": "pipeline.preparation",
    "PrepareGnnTrainingDataContext": "pipeline.preparation",
    "PrepareGnnTrainingDataStep": "pipeline.preparation",
    "PreparedGnnTrainingData": "pipeline.preparation",
    "PreparedGnnTrainingInstance": "pipeline.preparation",
    "GnnTrainingDataPreparationConfig": "pipeline.preparation",
    "GnnTrainingDataPreparationService": "pipeline.preparation",
    "CONTEXT_CONSTRUCTION_STRATEGIES": "pipeline.preparation",
    "ContextConstructionDefinition": "pipeline.preparation",
    "DATASET_CACHE_ROOT": "pipeline.preparation",
    "DATASET_LOADERS": "pipeline.preparation",
    "DatasetDefinition": "pipeline.preparation",
    "DatasetLoaderDefinition": "pipeline.preparation",
    "GNN_HIDDEN_DIMENSION_OPTIONS": "pipeline.preparation",
    "GNN_ARCHITECTURES": "pipeline.preparation",
    "GNN_LAYER_COUNT_OPTIONS": "pipeline.preparation",
    "GnnHiddenDimensionDefinition": "pipeline.preparation",
    "GnnArchitectureDefinition": "pipeline.preparation",
    "GnnArchitectureOptionDefinition": "pipeline.preparation",
    "GnnLayerCountDefinition": "pipeline.preparation",
    "LoadDatasetStep": "pipeline.preparation",
    "LoadedDataset": "pipeline.preparation",
    "LlmModelDefinition": "pipeline.preparation",
    "NODE_CLASSIFIERS": "pipeline.preparation",
    "NodeClassifierDefinition": "pipeline.preparation",
    "OPENAI_EMBEDDING_MODELS": "pipeline.preparation",
    "OpenAiEmbeddingModelDefinition": "pipeline.preparation",
    "PIPELINE_DATASETS": "pipeline.preparation",
    "PipelineConfigurationInput": "pipeline.preparation",
    "PreparedWebQSPGraphDataset": "pipeline.preparation",
    "RECOMMENDED_CONTEXT_CONSTRUCTION_STRATEGY_ID": "pipeline.preparation",
    "RECOMMENDED_ENTITY_EMBEDDING_MODEL_ID": "pipeline.preparation",
    "RECOMMENDED_GNN_HIDDEN_DIMENSION": "pipeline.preparation",
    "RECOMMENDED_GNN_LAYER_COUNT": "pipeline.preparation",
    "RECOMMENDED_MAIN_LLM_MODEL_ID": "pipeline.preparation",
    "RECOMMENDED_NODE_CLASSIFIER_ID": "pipeline.preparation",
    "RECOMMENDED_QUESTION_EMBEDDING_MODEL_ID": "pipeline.preparation",
    "RECOMMENDED_RELATION_EMBEDDING_MODEL_ID": "pipeline.preparation",
    "RECOMMENDED_SUBGRAPH_CONSTRUCTION_ALGORITHM_ID": "pipeline.preparation",
    "SelectedDataset": "pipeline.preparation",
    "SelectDatasetStep": "pipeline.preparation",
    "SHARED_LLM_MODELS": "pipeline.preparation",
    "SUBGRAPH_CONSTRUCTION_ALGORITHMS": "pipeline.preparation",
    "SubgraphConstructionDefinition": "pipeline.preparation",
    "TrainGnnAnswerRetrieverContext": "pipeline.preparation",
    "TrainGnnAnswerRetrieverStep": "pipeline.preparation",
    "TrainedGnnAnswerRetriever": "pipeline.preparation",
    "WEBQSP_DATASET_ID": "pipeline.preparation",
    "WebQSPEntityMappingSummary": "pipeline.preparation",
    "WebQSPProcessedInstance": "pipeline.preparation",
    "WebQSPVocabularyStore": "pipeline.preparation",
    "DatasetLoadingException": "pipeline.preparation.exceptions",
    "GnnAnswerRetrieverEvaluationException": "pipeline.preparation.exceptions",
    "GnnAnswerRetrieverModelRunException": "pipeline.preparation.exceptions",
    "GnnAnswerRetrieverTrainingException": "pipeline.preparation.exceptions",
    "InvalidContextConstructionSelectionException": "pipeline.preparation.exceptions",
    "InvalidEntityEmbeddingModelSelectionException": "pipeline.preparation.exceptions",
    "InvalidGnnHiddenDimensionSelectionException": "pipeline.preparation.exceptions",
    "InvalidGnnArchitectureConfigurationException": "pipeline.preparation.exceptions",
    "InvalidGnnArchitectureSelectionException": "pipeline.preparation.exceptions",
    "InvalidGnnLayerCountSelectionException": "pipeline.preparation.exceptions",
    "InvalidInteractiveConfigurationInputException": "pipeline.preparation.exceptions",
    "InvalidLlmProviderSelectionException": "pipeline.preparation.exceptions",
    "InvalidMainLlmSelectionException": "pipeline.preparation.exceptions",
    "InvalidNodeClassifierSelectionException": "pipeline.preparation.exceptions",
    "InvalidQuestionEmbeddingModelSelectionException": "pipeline.preparation.exceptions",
    "InvalidRelationEmbeddingModelSelectionException": "pipeline.preparation.exceptions",
    "InvalidSubgraphConstructionSelectionException": "pipeline.preparation.exceptions",
    "MalformedDatasetException": "pipeline.preparation.exceptions",
    "MalformedWebQSPExampleException": "pipeline.preparation.exceptions",
    "MissingHuggingFaceDatasetsDependencyException": "pipeline.preparation.exceptions",
    "OpenAiEmbeddingConfigurationException": "pipeline.preparation.exceptions",
    "ProcessedDatasetStorageException": "pipeline.preparation.exceptions",
    "UnsupportedDatasetLoaderException": "pipeline.preparation.exceptions",
    "UnsupportedDatasetProcessorException": "pipeline.preparation.exceptions",
    "UnsupportedDatasetSelectionException": "pipeline.preparation.exceptions",
    "AbstractDatasetLoaderService": "pipeline.preparation.services",
    "HuggingFaceWebQSPDatasetLoaderService": "pipeline.preparation.services",
    "LangChainOpenAiTextEmbeddingService": "pipeline.preparation.services",
    "SelectionService": "pipeline.preparation.services",
    "TextEmbeddingCache": "pipeline.preparation.services",
    "WebQSPEmbeddingCacheService": "pipeline.preparation.services",
    "WebQSPEntityNameMappingService": "pipeline.preparation.services",
    "WebQSPLocalGraphProcessorService": "pipeline.preparation.services",
    "WebQSPLocalGraphStorageService": "pipeline.preparation.services",
    "AnswerCandidateScore": "pipeline.evaluation",
    "BuildReasoningSamplesFromGnnEvaluationContext": "pipeline.evaluation",
    "BuildReasoningSamplesFromGnnEvaluationStep": "pipeline.evaluation",
    "BuildEvidenceSubgraphsBatchStep": "pipeline.evaluation",
    "BuildEvidenceSubgraphsContext": "pipeline.evaluation",
    "BuiltReasoningSamples": "pipeline.evaluation",
    "CandidateNodeScore": "pipeline.evaluation",
    "CandidateNodeScores": "pipeline.evaluation",
    "ComputeFinalResultsContext": "pipeline.evaluation",
    "ComputeFinalResultsStep": "pipeline.evaluation",
    "EvaluationSample": "pipeline.evaluation",
    "EvaluateGnnAnswerRetrieverContext": "pipeline.evaluation",
    "EvaluateGnnAnswerRetrieverStep": "pipeline.evaluation",
    "EvaluatedAnswerRetrievalInstance": "pipeline.evaluation",
    "ExtractShortestPathsBatchStep": "pipeline.evaluation",
    "ExtractShortestPathsStep": "pipeline.evaluation",
    "ExtractedReasoningPaths": "pipeline.evaluation",
    "ExtractedReasoningPathsBatch": "pipeline.evaluation",
    "ExplanationGroundingMetrics": "pipeline.evaluation",
    "FinalAnswerMetrics": "pipeline.evaluation",
    "FinalReasoningMetrics": "pipeline.evaluation",
    "FinalResultsConfig": "pipeline.evaluation",
    "FinalResultsEvaluationException": "pipeline.evaluation",
    "FinalResultsEvaluationOutcome": "pipeline.evaluation",
    "FinalResultsEvaluationResult": "pipeline.evaluation",
    "FinalResultsEvaluationService": "pipeline.evaluation",
    "FinalResultsStorageResult": "pipeline.evaluation",
    "GeneratedAnswerForPrediction": "pipeline.evaluation",
    "GeneratedFinalAnswer": "pipeline.evaluation",
    "GeneratedFinalAnswersBatch": "pipeline.evaluation",
    "GenerateAndSaveFinalAnswersBatchesContext": "pipeline.evaluation",
    "GenerateAndSaveFinalAnswersBatchesStep": "pipeline.evaluation",
    "GenerateFinalAnswerStep": "pipeline.evaluation",
    "GenerateFinalAnswersBatchStep": "pipeline.evaluation",
    "GnnAnswerRetrieverEvaluationConfig": "pipeline.evaluation",
    "GnnAnswerRetrieverEvaluationResult": "pipeline.evaluation",
    "GnnAnswerRetrieverMetrics": "pipeline.evaluation",
    "GnnPredictionCandidateScoringStep": "pipeline.evaluation",
    "GnnRetrieverResultsService": "pipeline.evaluation",
    "GoldAnswerScore": "pipeline.evaluation",
    "GraphTriple": "pipeline.evaluation",
    "InvalidEvaluationSampleException": "pipeline.evaluation",
    "LangChainOpenAiAnswerGenerationService": "pipeline.evaluation",
    "LlmAnswerGenerationException": "pipeline.evaluation",
    "LlmInferenceStoragePayload": "pipeline.evaluation",
    "LlmInferenceStorageResult": "pipeline.evaluation",
    "LlmInferenceStorageService": "pipeline.evaluation",
    "LogFinalResultsToWandbStep": "pipeline.evaluation",
    "LoadGnnAnswerRetrieverRunStep": "pipeline.evaluation",
    "LogRetrieverToWandbStep": "pipeline.evaluation",
    "LogTrainingToWandbStep": "pipeline.evaluation",
    "LogInferenceToWandbStep": "pipeline.evaluation",
    "LogEvidenceToWandbStep": "pipeline.evaluation",
    "MockCandidateNodeScoringStep": "pipeline.evaluation",
    "PerInstanceFinalResult": "pipeline.evaluation",
    "RankingMetrics": "pipeline.evaluation",
    "ReasoningPath": "pipeline.evaluation",
    "ReasoningPathsForPrediction": "pipeline.evaluation",
    "ReasoningSampleForPrediction": "pipeline.evaluation",
    "SaveInferenceRunStep": "pipeline.evaluation",
    "SaveEvidenceSubgraphsStep": "pipeline.evaluation",
    "SavedEvidenceSubgraphRun": "pipeline.evaluation",
    "SavedLlmInferenceRun": "pipeline.evaluation",
    "ShortestPathExtractionException": "pipeline.evaluation",
    "ShortestPathExtractionService": "pipeline.evaluation",
    "WandbFinalResultsConfig": "pipeline.evaluation",
    "WandbFinalResultsLogResult": "pipeline.evaluation",
    "WandbFinalResultsLoggingService": "pipeline.evaluation",
}


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


__all__ = sorted(_EXPORT_MODULES)
