"""Preparation-specific exceptions."""

from pipeline.preparation.exceptions.exceptions import (
    DatasetLoadingException,
    GnnAnswerRetrieverEvaluationException,
    GnnAnswerRetrieverModelRunException,
    GnnAnswerRetrieverTrainingException,
    InvalidContextConstructionSelectionException,
    InvalidEntityEmbeddingModelSelectionException,
    InvalidGnnHiddenDimensionSelectionException,
    InvalidGnnArchitectureConfigurationException,
    InvalidGnnArchitectureSelectionException,
    InvalidGnnLayerCountSelectionException,
    InvalidInteractiveConfigurationInputException,
    InvalidLlmProviderSelectionException,
    InvalidMainLlmSelectionException,
    InvalidNodeClassifierSelectionException,
    InvalidQuestionEmbeddingModelSelectionException,
    InvalidRelationEmbeddingModelSelectionException,
    InvalidSubgraphConstructionSelectionException,
    MalformedDatasetException,
    MalformedWebQSPExampleException,
    MissingHuggingFaceDatasetsDependencyException,
    OpenAiEmbeddingConfigurationException,
    ProcessedDatasetStorageException,
    QdrantEmbeddingStoreException,
    UnsupportedDatasetLoaderException,
    UnsupportedDatasetProcessorException,
    UnsupportedDatasetSelectionException,
)
from pipeline.exceptions import PipelineException

__all__ = [
    "DatasetLoadingException",
    "GnnAnswerRetrieverEvaluationException",
    "GnnAnswerRetrieverModelRunException",
    "GnnAnswerRetrieverTrainingException",
    "InvalidContextConstructionSelectionException",
    "InvalidEntityEmbeddingModelSelectionException",
    "InvalidGnnHiddenDimensionSelectionException",
    "InvalidGnnArchitectureConfigurationException",
    "InvalidGnnArchitectureSelectionException",
    "InvalidGnnLayerCountSelectionException",
    "InvalidInteractiveConfigurationInputException",
    "InvalidLlmProviderSelectionException",
    "InvalidMainLlmSelectionException",
    "InvalidNodeClassifierSelectionException",
    "InvalidQuestionEmbeddingModelSelectionException",
    "InvalidRelationEmbeddingModelSelectionException",
    "InvalidSubgraphConstructionSelectionException",
    "MalformedDatasetException",
    "MalformedWebQSPExampleException",
    "MissingHuggingFaceDatasetsDependencyException",
    "OpenAiEmbeddingConfigurationException",
    "PipelineException",
    "ProcessedDatasetStorageException",
    "QdrantEmbeddingStoreException",
    "UnsupportedDatasetLoaderException",
    "UnsupportedDatasetProcessorException",
    "UnsupportedDatasetSelectionException",
]
